version: "2"

volumes:
  
  mongodb-data:
    driver: local

services:

  mongodb:
    container_name: mongodb
    image: mongo:3.4.9
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  nodejs:
    container_name: nodejs
    image: node:8.6.0-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "node_modules/.bin/nodemon -L --exec npm start"
    links:
      - mongodb